import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const problems = [
  // EASY (17 problems)
  {
    title: 'Two Sum',
    slug: 'two-sum',
    difficulty: 'easy',
    description: 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    inputFormat: 'The first line contains an array of integers `nums`.\n\nThe second line contains an integer `target`.',
    outputFormat: 'Return an array of two integers representing the indices of the two numbers that add up to target.',
    examples: [
      { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 9, we return [0, 1]' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]', explanation: 'Because nums[1] + nums[2] == 6, we return [1, 2]' },
    ],
    constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9', '-10^9 <= target <= 10^9', 'Only one valid answer exists.'],
    hints: ['A really brute force way would be to search for all possible pairs of numbers but that would be too slow. Again, it\'s best to try out brute force solutions for just for completeness. It is from these brute force solutions that you can come up with optimizations.', 'So, if we fix one of the numbers, say x, we have to loop through the array to find the other number, y, such that x + y = target which is exactly what the hash map does.'],
    testCases: [{ input: '[2,7,11,15]\n9', output: '[0,1]' }, { input: '[3,2,4]\n6', output: '[1,2]' }],
    topics: ['arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Reverse String',
    slug: 'reverse-string',
    difficulty: 'easy',
    description: 'Write a function that reverses a string. The input string is given as an array of characters s.',
    examples: [{ input: 's = ["h","e","l","l","o"]', output: '["o","l","l","e","h"]' }],
    constraints: ['1 <= s.length <= 10^5', 's[i] is a printable ascii character'],
    testCases: [{ input: '["h","e","l","l","o"]', output: '["o","l","l","e","h"]' }],
    topics: ['strings', 'two_pointers'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    difficulty: 'easy',
    description: 'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.\n\nAn input string is valid if:\n\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
    inputFormat: 'A single line containing the string `s` consisting of parentheses characters.',
    outputFormat: 'Return `true` if the string is valid, otherwise return `false`.',
    examples: [
      { input: 's = "()"', output: 'true', explanation: 'The string contains properly matched parentheses.' },
      { input: 's = "()[]{}"', output: 'true', explanation: 'All brackets are properly matched.' },
      { input: 's = "(]"', output: 'false', explanation: 'The closing bracket does not match the opening bracket.' },
    ],
    constraints: ['1 <= s.length <= 10^4', 's consists of parentheses only \'()[]{}\''],
    hints: ['Use a stack data structure to keep track of opening brackets.', 'When you encounter a closing bracket, check if it matches the most recent opening bracket.'],
    testCases: [{ input: '()', output: 'true' }, { input: '()[]{}', output: 'true' }, { input: '(]', output: 'false' }],
    topics: ['stacks', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    difficulty: 'easy',
    description: 'You are given the heads of two sorted linked lists. Merge the two lists into one sorted list.',
    examples: [{ input: 'l1 = [1,2,4], l2 = [1,3,4]', output: '[1,1,2,3,4,4]' }],
    constraints: ['Both lists are sorted in non-decreasing order'],
    testCases: [{ input: '[1,2,4]\n[1,3,4]', output: '[1,1,2,3,4,4]' }],
    topics: ['linked_lists', 'recursion'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    difficulty: 'easy',
    description: 'Given an integer array `nums`, find the subarray with the largest sum, and return its sum.',
    inputFormat: 'The first line contains an integer `n` (1 <= n <= 10^5), the size of the array.\n\nThe second line contains `n` integers separated by spaces.',
    outputFormat: 'Return a single integer representing the sum of the subarray with the largest sum.',
    examples: [
      { input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6', explanation: 'The subarray [4,-1,2,1] has the largest sum 6.' },
      { input: 'nums = [1]', output: '1', explanation: 'The subarray [1] has the largest sum 1.' },
    ],
    constraints: ['1 <= nums.length <= 10^5', '-10^4 <= nums[i] <= 10^4'],
    hints: ['Think about how to solve this problem using dynamic programming.', 'Consider Kadane\'s algorithm for an optimal solution.'],
    testCases: [{ input: '[-2,1,-3,4,-1,2,1,-5,4]', output: '6' }, { input: '[1]', output: '1' }, { input: '[5,4,-1,7,8]', output: '23' }],
    topics: ['arrays', 'dynamic_programming'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-sell-stock',
    difficulty: 'easy',
    description: 'You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit.',
    examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '5' }],
    constraints: ['1 <= prices.length <= 10^5'],
    testCases: [{ input: '[7,1,5,3,6,4]', output: '5' }],
    topics: ['arrays', 'dynamic_programming'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    difficulty: 'easy',
    description: 'Given an integer array nums, return true if any value appears at least twice in the array.',
    examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }],
    constraints: ['1 <= nums.length <= 10^5'],
    testCases: [{ input: '[1,2,3,1]', output: 'true' }],
    topics: ['arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Binary Search',
    slug: 'binary-search',
    difficulty: 'easy',
    description: 'Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums.',
    examples: [{ input: 'nums = [-1,0,3,5,9,12], target = 9', output: '4' }],
    constraints: ['All the integers in nums are unique'],
    testCases: [{ input: '[-1,0,3,5,9,12]\n9', output: '4' }],
    topics: ['binary_search', 'arrays'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Linked List Cycle',
    slug: 'linked-list-cycle',
    difficulty: 'easy',
    description: 'Given head, the head of a linked list, determine if the linked list has a cycle in it.',
    examples: [{ input: 'head = [3,2,0,-4]', output: 'true' }],
    constraints: ['The number of the nodes in the list is in the range [0, 10^4]'],
    testCases: [{ input: '[3,2,0,-4]', output: 'true' }],
    topics: ['linked_lists', 'two_pointers'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Invert Binary Tree',
    slug: 'invert-binary-tree',
    difficulty: 'easy',
    description: 'Given the root of a binary tree, invert the tree, and return its root.',
    examples: [{ input: 'root = [4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]' }],
    constraints: ['The number of nodes in the tree is in the range [0, 100]'],
    testCases: [{ input: '[4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]' }],
    topics: ['trees', 'breadth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Maximum Depth of Binary Tree',
    slug: 'maximum-depth-binary-tree',
    difficulty: 'easy',
    description: 'Given the root of a binary tree, return its maximum depth.',
    examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: '3' }],
    constraints: ['The number of nodes is in the range [0, 10^4]'],
    testCases: [{ input: '[3,9,20,null,null,15,7]', output: '3' }],
    topics: ['trees', 'depth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Same Tree',
    slug: 'same-tree',
    difficulty: 'easy',
    description: 'Given the roots of two binary trees p and q, write a function to check if they are the same or not.',
    examples: [{ input: 'p = [1,2,3], q = [1,2,3]', output: 'true' }],
    constraints: ['Both trees have the same number of nodes'],
    testCases: [{ input: '[1,2,3]\n[1,2,3]', output: 'true' }],
    topics: ['trees', 'depth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Subarray Sum Equals K',
    slug: 'subarray-sum-equals-k',
    difficulty: 'easy',
    description: 'Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.',
    examples: [{ input: 'nums = [1,1,1], k = 2', output: '2' }],
    constraints: ['1 <= nums.length <= 2 * 10^4'],
    testCases: [{ input: '[1,1,1]\n2', output: '2' }],
    topics: ['arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Moving Average from Data Stream',
    slug: 'moving-average-data-stream',
    difficulty: 'easy',
    description: 'Calculate the moving average of sliding window of size k.',
    examples: [{ input: 'MovingAverage(3)\nadd(1)\nadd(10)\nadd(3)\nadd(5)', output: '[1, 5.5, 4.67, 6]' }],
    constraints: ['1 <= k <= 1000'],
    testCases: [{ input: '3\n[1,10,3,5]', output: '[1,5.5,4.67,6]' }],
    topics: ['arrays', 'design', 'queues'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Count Elements',
    slug: 'count-elements',
    difficulty: 'easy',
    description: 'Given an integer array arr, count how many elements x there are such that x + 1 is also in arr.',
    examples: [{ input: 'arr = [1,2,3]', output: '2' }],
    constraints: ['1 <= arr.length <= 1000'],
    testCases: [{ input: '[1,2,3]', output: '2' }],
    topics: ['arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Middle of the Linked List',
    slug: 'middle-linked-list',
    difficulty: 'easy',
    description: 'Given the head of a singly linked list, return the middle node of the linked list.',
    examples: [{ input: 'head = [1,2,3,4,5]', output: '[3,4,5]' }],
    constraints: ['The number of nodes is in the range [1, 100]'],
    testCases: [{ input: '[1,2,3,4,5]', output: '[3,4,5]' }],
    topics: ['linked_lists', 'two_pointers'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Power of Three',
    slug: 'power-of-three',
    difficulty: 'easy',
    description: 'Given an integer n, return true if it is a power of three.',
    examples: [{ input: 'n = 27', output: 'true' }],
    constraints: ['-2^31 <= n <= 2^31 - 1'],
    testCases: [{ input: '27', output: 'true' }, { input: '0', output: 'false' }],
    topics: ['math', 'recursion'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  // MEDIUM (18 problems)
  {
    title: 'Longest Substring Without Repeating Characters',
    slug: 'longest-substring-without-repeating',
    difficulty: 'medium',
    description: 'Given a string s, find the length of the longest substring without repeating characters.',
    examples: [{ input: 's = "abcabcbb"', output: '3' }],
    constraints: ['0 <= s.length <= 5 * 10^4'],
    testCases: [{ input: '"abcabcbb"', output: '3' }],
    topics: ['strings', 'sliding_window', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Container With Most Water',
    slug: 'container-with-most-water',
    difficulty: 'medium',
    description: 'You are given an integer array height of length n. Find two lines that together with the x-axis form a container.',
    examples: [{ input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49' }],
    constraints: ['n == height.length', '2 <= n <= 10^5'],
    testCases: [{ input: '[1,8,6,2,5,4,8,3,7]', output: '49' }],
    topics: ['arrays', 'two_pointers', 'greedy'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: '3Sum',
    slug: '3sum',
    difficulty: 'medium',
    description: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.',
    examples: [{ input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }],
    constraints: ['3 <= nums.length <= 3000'],
    testCases: [{ input: '[-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }],
    topics: ['arrays', 'sorting', 'two_pointers'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Group Anagrams',
    slug: 'group-anagrams',
    difficulty: 'medium',
    description: 'Given an array of strings strs, group the anagrams together.',
    examples: [{ input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }],
    constraints: ['1 <= strs.length <= 10^4'],
    testCases: [{ input: '["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }],
    topics: ['strings', 'hash_map', 'sorting'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self',
    difficulty: 'medium',
    description: 'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].',
    examples: [{ input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' }],
    constraints: ['2 <= nums.length <= 10^5'],
    testCases: [{ input: '[1,2,3,4]', output: '[24,12,8,6]' }],
    topics: ['arrays', 'prefix_sum'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Valid Sudoku',
    slug: 'valid-sudoku',
    difficulty: 'medium',
    description: 'Determine if a 9x9 Sudoku board is valid.',
    examples: [{ input: 'board = [["5","3",".",".","7",".",".",".","."],...]', output: 'true' }],
    constraints: ['board.length == 9', 'board[i].length == 9'],
    testCases: [{ input: '[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]', output: 'true' }],
    topics: ['arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Coin Change',
    slug: 'coin-change',
    difficulty: 'medium',
    description: 'You are given an integer array coins representing coins of different denominations and an integer amount. Return the fewest number of coins that you need to make up that amount.',
    examples: [{ input: 'coins = [1,2,5], amount = 11', output: '3' }],
    constraints: ['1 <= coins.length <= 12'],
    testCases: [{ input: '[1,2,5]\n11', output: '3' }],
    topics: ['dynamic_programming', 'arrays'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Longest Increasing Subsequence',
    slug: 'longest-increasing-subsequence',
    difficulty: 'medium',
    description: 'Given an integer array nums, return the length of the longest strictly increasing subsequence.',
    examples: [{ input: 'nums = [10,9,2,5,3,7,101,18]', output: '4' }],
    constraints: ['1 <= nums.length <= 2500'],
    testCases: [{ input: '[10,9,2,5,3,7,101,18]', output: '4' }],
    topics: ['dynamic_programming', 'binary_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Number of Islands',
    slug: 'number-of-islands',
    difficulty: 'medium',
    description: 'Given an m x n 2D binary grid grid which represents a map of 1s (land) and 0s (water), return the number of islands.',
    examples: [{ input: 'grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', output: '1' }],
    constraints: ['m == grid.length', 'n == grid[i].length'],
    testCases: [{ input: '[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', output: '1' }],
    topics: ['graphs', 'depth_first_search', 'breadth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Clone Graph',
    slug: 'clone-graph',
    difficulty: 'medium',
    description: 'Given a reference of a node in a connected undirected graph, return a deep copy of the graph.',
    examples: [{ input: 'adjList = [[2,4],[1,3],[2,4],[1,3]]', output: '[[2,4],[1,3],[2,4],[1,3]]' }],
    constraints: ['The number of nodes in the graph is in the range [0, 100]'],
    testCases: [{ input: '[[2,4],[1,3],[2,4],[1,3]]', output: '[[2,4],[1,3],[2,4],[1,3]]' }],
    topics: ['graphs', 'depth_first_search', 'breadth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Course Schedule',
    slug: 'course-schedule',
    difficulty: 'medium',
    description: 'There are a total of numCourses courses you have to take. Some courses have prerequisites. Return true if you can finish all courses.',
    examples: [{ input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true' }],
    constraints: ['1 <= numCourses <= 2000'],
    testCases: [{ input: '2\n[[1,0]]', output: 'true' }],
    topics: ['graphs', 'topological_sort'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Implement Trie',
    slug: 'implement-trie',
    difficulty: 'medium',
    description: 'Implement a trie with insert, search, and startsWith methods.',
    examples: [{ input: '["Trie","insert","search","search","startsWith"]', output: '[null,null,true,false,true]' }],
    constraints: ['1 <= word.length, prefix.length <= 2000'],
    testCases: [{ input: '["insert","search","search","startsWith"]\n["apple","apple","app","app"]', output: '[null,true,false,true]' }],
    topics: ['trees', 'design', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Kth Largest Element in an Array',
    slug: 'kth-largest-element',
    difficulty: 'medium',
    description: 'Given an integer array nums and an integer k, return the kth largest element in the array.',
    examples: [{ input: 'nums = [3,2,1,5,6,4], k = 2', output: '5' }],
    constraints: ['1 <= k <= nums.length <= 10^5'],
    testCases: [{ input: '[3,2,1,5,6,4]\n2', output: '5' }],
    topics: ['arrays', 'sorting', 'heaps'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Top K Frequent Elements',
    slug: 'top-k-frequent-elements',
    difficulty: 'medium',
    description: 'Given an integer array nums and an integer k, return the k most frequent elements.',
    examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' }],
    constraints: ['1 <= nums.length <= 10^5'],
    testCases: [{ input: '[1,1,1,2,2,3]\n2', output: '[1,2]' }],
    topics: ['arrays', 'hash_map', 'heaps'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Search in Rotated Sorted Array',
    slug: 'search-rotated-sorted-array',
    difficulty: 'medium',
    description: 'Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not.',
    examples: [{ input: 'nums = [4,5,6,7,0,1,2], target = 0', output: '4' }],
    constraints: ['1 <= nums.length <= 5000'],
    testCases: [{ input: '[4,5,6,7,0,1,2]\n0', output: '4' }],
    topics: ['arrays', 'binary_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Decode Ways',
    slug: 'decode-ways',
    difficulty: 'medium',
    description: 'A message containing letters from A-Z can be encoded into numbers using the mapping. Return the number of ways to decode it.',
    examples: [{ input: 's = "12"', output: '2' }],
    constraints: ['1 <= s.length <= 100'],
    testCases: [{ input: '"12"', output: '2' }],
    topics: ['dynamic_programming', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Generate Parentheses',
    slug: 'generate-parentheses',
    difficulty: 'medium',
    description: 'Given n pairs of parentheses, generate all combinations of well-formed parentheses.',
    examples: [{ input: 'n = 3', output: ['((()))', '(()())', '(())()', '()(())', '()()()'] }],
    constraints: ['1 <= n <= 8'],
    testCases: [{ input: '3', output: '["((()))","(()())","(())()","()(())","()()()"]' }],
    topics: ['backtracking', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Letter Combinations of a Phone Number',
    slug: 'letter-combinations-phone-number',
    difficulty: 'medium',
    description: 'Given a string containing digits from 2-9 inclusive, return all possible letter combinations.',
    examples: [{ input: 'digits = "23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }],
    constraints: ['0 <= digits.length <= 4'],
    testCases: [{ input: '"23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }],
    topics: ['backtracking', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Longest Palindromic Substring',
    slug: 'longest-palindromic-substring',
    difficulty: 'medium',
    description: 'Given a string s, return the longest palindromic substring in s.',
    examples: [{ input: 's = "babad"', output: '"bab"' }],
    constraints: ['1 <= s.length <= 1000'],
    testCases: [{ input: '"babad"', output: '"bab"' }],
    topics: ['strings', 'dynamic_programming'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  // HARD (15 problems)
  {
    title: 'Merge k Sorted Lists',
    slug: 'merge-k-sorted-lists',
    difficulty: 'hard',
    description: 'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list.',
    examples: [{ input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }],
    constraints: ['k == lists.length', '0 <= lists[i].length <= 500'],
    testCases: [{ input: '[[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }],
    topics: ['linked_lists', 'heaps', 'divide_and_conquer'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Trapping Rain Water',
    slug: 'trapping-rain-water',
    difficulty: 'hard',
    description: 'Given n non-negative integers representing an elevation map, compute how much water it can trap after raining.',
    examples: [{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    constraints: ['n == height.length', '1 <= n <= 2 * 10^4'],
    testCases: [{ input: '[0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    topics: ['arrays', 'two_pointers', 'stacks'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Word Ladder',
    slug: 'word-ladder',
    difficulty: 'hard',
    description: 'Given two words beginWord and endWord, return the number of letters in the shortest transformation sequence.',
    examples: [{ input: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]', output: '5' }],
    constraints: ['1 <= beginWord.length <= 10'],
    testCases: [{ input: '"hit"\n"cog"\n["hot","dot","dog","lot","log","cog"]', output: '5' }],
    topics: ['graphs', 'breadth_first_search', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Median of Two Sorted Arrays',
    slug: 'median-two-sorted-arrays',
    difficulty: 'hard',
    description: 'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.',
    examples: [{ input: 'nums1 = [1,3], nums2 = [2]', output: '2.0' }],
    constraints: ['nums1.length == m', 'nums2.length == n'],
    testCases: [{ input: '[1,3]\n[2]', output: '2.0' }],
    topics: ['arrays', 'binary_search', 'divide_and_conquer'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Regular Expression Matching',
    slug: 'regular-expression-matching',
    difficulty: 'hard',
    description: 'Given an input string s and a pattern p, implement regular expression matching with support for . and *.',
    examples: [{ input: 's = "aa", p = "a"', output: 'false' }],
    constraints: ['1 <= s.length <= 20'],
    testCases: [{ input: '"aa"\n"a"', output: 'false' }],
    topics: ['strings', 'dynamic_programming', 'backtracking'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'N-Queens',
    slug: 'n-queens',
    difficulty: 'hard',
    description: 'The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Return all distinct solutions.',
    examples: [{ input: 'n = 4', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }],
    constraints: ['1 <= n <= 9'],
    testCases: [{ input: '4', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }],
    topics: ['backtracking'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Serialize and Deserialize Binary Tree',
    slug: 'serialize-deserialize-binary-tree',
    difficulty: 'hard',
    description: 'Design an algorithm to serialize and deserialize a binary tree.',
    examples: [{ input: 'root = [1,2,3,null,null,4,5]', output: '[1,2,3,null,null,4,5]' }],
    constraints: ['The number of nodes in the tree is in the range [0, 10^4]'],
    testCases: [{ input: '[1,2,3,null,null,4,5]', output: '[1,2,3,null,null,4,5]' }],
    topics: ['trees', 'design', 'breadth_first_search'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Minimum Window Substring',
    slug: 'minimum-window-substring',
    difficulty: 'hard',
    description: 'Given two strings s and t, return the minimum window substring of s such that every character in t is included in the window.',
    examples: [{ input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' }],
    constraints: ['m == s.length', 'n == t.length'],
    testCases: [{ input: '"ADOBECODEBANC"\n"ABC"', output: '"BANC"' }],
    topics: ['strings', 'sliding_window', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Binary Tree Maximum Path Sum',
    slug: 'binary-tree-maximum-path-sum',
    difficulty: 'hard',
    description: 'Given a non-empty binary tree, find the maximum path sum.',
    examples: [{ input: 'root = [1,2,3]', output: '6' }],
    constraints: ['The number of nodes in the tree is in the range [0, 3 * 10^4]'],
    testCases: [{ input: '[1,2,3]', output: '6' }],
    topics: ['trees', 'depth_first_search', 'dynamic_programming'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Alien Dictionary',
    slug: 'alien-dictionary',
    difficulty: 'hard',
    description: 'Given a sorted dictionary of an alien language, find the order of characters.',
    examples: [{ input: '["wrt","wrf","er","ett","rftt"]', output: '"wertf"' }],
    constraints: ['1 <= words.length <= 100'],
    testCases: [{ input: '["wrt","wrf","er","ett","rftt"]', output: '"wertf"' }],
    topics: ['graphs', 'topological_sort', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Longest Valid Parentheses',
    slug: 'longest-valid-parentheses',
    difficulty: 'hard',
    description: 'Given a string containing just the characters "(" and ")", find the length of the longest valid (well-formed) parentheses substring.',
    examples: [{ input: 's = "(()"', output: '2' }],
    constraints: ['0 <= s.length <= 3 * 10^4'],
    testCases: [{ input: '"(()"', output: '2' }],
    topics: ['strings', 'dynamic_programming', 'stacks'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Edit Distance',
    slug: 'edit-distance',
    difficulty: 'hard',
    description: 'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.',
    examples: [{ input: 'word1 = "horse", word2 = "ros"', output: '3' }],
    constraints: ['0 <= word1.length, word2.length <= 500'],
    testCases: [{ input: '"horse"\n"ros"', output: '3' }],
    topics: ['dynamic_programming', 'strings'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Largest Rectangle in Histogram',
    slug: 'largest-rectangle-histogram',
    difficulty: 'hard',
    description: 'Given an array of integers heights representing the histogram, find the area of the largest rectangle in the histogram.',
    examples: [{ input: 'heights = [2,1,5,6,2,3]', output: '10' }],
    constraints: ['1 <= heights.length <= 10^5'],
    testCases: [{ input: '[2,1,5,6,2,3]', output: '10' }],
    topics: ['arrays', 'stacks', 'monotonic_stack'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Maximal Rectangle',
    slug: 'maximal-rectangle',
    difficulty: 'hard',
    description: 'Given a rows x cols binary matrix filled with 0s and 1s, find the largest rectangle containing only 1s and return its area.',
    examples: [{ input: 'matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', output: '6' }],
    constraints: ['rows == matrix.length', 'cols == matrix[i].length'],
    testCases: [{ input: '[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', output: '6' }],
    topics: ['arrays', 'dynamic_programming', 'stacks'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
  {
    title: 'Frog Jump',
    slug: 'frog-jump',
    difficulty: 'hard',
    description: 'A frog is crossing a river. The river is divided into some number of units, and at each unit, there may or may not exist a stone. Return true if the frog can cross the river.',
    examples: [{ input: 'stones = [0,1,3,5,6,7,8,12,17]', output: 'true' }],
    constraints: ['2 <= stones.length <= 2000'],
    testCases: [{ input: '[0,1,3,5,6,7,8,12,17]', output: 'true' }],
    topics: ['dynamic_programming', 'arrays', 'hash_map'],
    timeLimit: 5000,
    memoryLimit: 256,
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing problems
  await prisma.problem.deleteMany();

  // Insert problems
  for (const problem of problems) {
    await prisma.problem.create({
      data: {
        title: problem.title,
        slug: problem.slug,
        difficulty: problem.difficulty,
        description: problem.description,
        inputFormat: problem.inputFormat,
        outputFormat: problem.outputFormat,
        examples: problem.examples,
        constraints: problem.constraints,
        hints: problem.hints,
        testCases: problem.testCases,
        topics: problem.topics,
        timeLimit: problem.timeLimit,
        memoryLimit: problem.memoryLimit,
      },
    });
  }

  console.log(`Seeded ${problems.length} problems`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
